---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - 'create'
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - '*'
    resourceNames:
      - "alibabacloud-erdma-controller-webhook-cert"
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - '*'
    resourceNames:
      - "alibabacloud-erdma-controller"
  - apiGroups:
      - network.alibabacloud.com
    resources:
      - 'erdmadevices'
      - 'erdmadevices/status'
    verbs:
      - '*'
