apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "alibabacloud-erdma-controller.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "region": "{{ .Values.config.region }}",
      "manageNonOwnedENIs": {{ .Values.config.manageNonOwnedENIs }},
      "controllerNamespace": "kube-system",
      "controllerName": "alibabacloud-erdma-controller",
      "clusterDomain": "cluster.local",
      "certDir": "/var/lib/certDir",
      "enableDevicePlugin": {{ .Values.config.enableDevicePlugin }},
      "enableWebhook": {{ .Values.config.enableWebhook }},
      "smcInitImage": "{{ .Values.config.smcInitImage }}",
      "enableInitContainerInject": {{ .Values.config.enableInitContainerInject }},
      "nodeSelector": {{ .Values.nodeSelector | toJson }}
    }
