apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alibabacloud-erdma-agent
  labels:
    {{- include "alibabacloud-erdma-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "alibabacloud-erdma-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alibabacloud-erdma-controller.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alibabacloud-erdma-controller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              add:
                - SYS_MODULE
                - SYS_ADMIN
                - NET_ADMIN
                - SYS_PTRACE
          command:
            - /usr/local/bin/agent
            {{ if .Values.agent.preferDriver }}
            - --prefer-driver
            - {{ .Values.agent.preferDriver }}
            {{ end }}
            {{ if .Values.agent.allocateAllDevices }}
            - --allocate-all-devices
            {{ end }}
            {{ if not .Values.config.enableWebhook }}
            - --deviceplugin-prestart-container
            {{ end }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /var/lib/kubelet/device-plugins
            name: device-plugin
          - mountPath: /run/containerd
            name: cri-dir
          - mountPath: /var/lib/kubelet/pod-resources/
            name: pod-resource-dir
          - mountPath: /var/run/
            name: var-run
      volumes:
      - name: pod-resource-dir
        hostPath:
          path: /var/lib/kubelet/pod-resources/
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: cri-dir
        hostPath:
          path: /run/containerd
          type: "Directory"
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: "Directory"
      - name: var-run
        hostPath:
          path: /var/run/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
