{{- if not .Values.config.localERIDiscovery }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibabacloud-erdma-controller
  labels:
    {{- include "alibabacloud-erdma-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "alibabacloud-erdma-controller.selectorLabels" . | nindent 6 }}
      tier: controller
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alibabacloud-erdma-controller.selectorLabels" . | nindent 8 }}
        tier: controller
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alibabacloud-erdma-controller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - name: webhook
              containerPort: 9443
              protocol: TCP
          volumeMounts:
            - name: config-vol
              mountPath: /etc/erdma-controller
            - name: secret-vol
              mountPath: /etc/erdma-controller-credential
            - name: webhook-vol
              mountPath: /var/lib/certDir
      volumes:
      - name: config-vol
        configMap:
          name: {{ .Release.Name }}
          items:
            - key: config.json
              path: config.json
      - name: secret-vol
        secret:
          secretName: {{ .Release.Name }}
      - name: webhook-vol
        emptyDir: { }
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
