apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "alibabacloud-erdma-controller.labels" . | nindent 4 }}
stringData:
  credential.json: |
    {
      "accessKeyID": "{{ .Values.credentials.accessKeyID }}",
      "accessKeySecret": "{{ .Values.credentials.accessKeySecret }}",
      "type": "{{ .Values.credentials.type }}"
    }
