apiVersion: v1
kind: Service
metadata:
  name: alibabacloud-erdma-controller
  labels:
    {{- include "alibabacloud-erdma-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: https
  selector:
    {{- include "alibabacloud-erdma-controller.selectorLabels" . | nindent 4 }}
