apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: erdma
  name: erdma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erdma
  template:
    metadata:
      annotations:
        network.alibabacloud.com/erdma-smcr: "true"
      labels:
        app: erdma
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: erdma
          resources:
            limits:
              aliyun/erdma: 1
